#!/usr/bin/python

import sys, traceback
import feedparser
import datetime
from urlparse import urlparse
import httplib2

try:
    from sqlite3 import dbapi2 as sqlite
except:
    from pysqlite2 import dbapi2 as sqlite

#on ubuntu 8.10 use sqlite3 from CLI instead of just sqlite
#create table podCast ( pName char(50), pUrl  char(2048), pId INTEGER PRIMARY KEY AUTOINCREMENT);
#pUrl is the feed item url, while pHref is the enclosure URL
#create table podItems (pTitle char(1024), pUrl char(2048), pHref char(2048), pId integer, itemId integer primary key autoincrement, gotten integer);

def createDb():
    c = con.cursor()
    c.execute("""create table podCast ( pName char(50), pUrl  char(2048), pId INTEGER PRIMARY KEY AUTOINCREMENT);""")
    c.execute("""create table podItems (pTitle char(1024), pUrl char(2048), pHref char(2048), pId integer, itemId integer primary key autoincrement);""")
    c.execute("""create table podConfig (pKey char(1024), pVal char(2048), cId integer primary key autoincrement);""")
    con.commit()

con=None

def isNewEntry(e):
    c = con.cursor()
    if 'title' in e:
        title = e['title'].encode("utf-8")
    else:
        title = 'New Item'
    if not 'enclosures' in e:
        return False

    t={"t": title, "u": str(e['link']), "h": str(e['enclosures'][0]['href'])}
    c.execute("select itemId from podItems where pTitle=:t and pUrl=:u and pHref=:h", t)
    ret=c.fetchall()
    #print repr(ret)
    if ret==[]:
        return True
    else:
        return False

#filesToDl=[]

def processEntries(entries, pid):
    newItemAr=[]
    for e in entries:
        if isNewEntry(e):
            link = e['link']
            if 'title' in e:
                title = e['title'].encode("utf-8")
            else:
                title = 'New Item'
            print "New item:", title, ":", link
            try:
                enc = e['enclosures'][0]['href']
                print "Download:", enc
                #filesToDl.append(enc)
                newItemAr.append(enc)
                t={"t": title, "u": str(link), "h": str(enc), "i": pid}
                #print repr(t)
                c = con.cursor()
                c.execute("insert into podItems(pTitle, pUrl, pHref, pId, gotten) values(:t,:u,:h,:i, 0);", t)
                con.commit()
            except KeyError, ke:
                print "ERROR----------------------------------"
                print "KEY ERROR:", ke.args[0]
                print e
    return newItemAr
        #else:
        #    print "Not new."

def fileNameFromUrl(url):
    uInfo = urlparse(url)
    return uInfo.path.split('/')[-1]

def getFile(url, filename):
    h = httplib2.Http(".cache")
    resp, data = h.request(u, "GET")
    
    f = open(filename, 'w')
    f.write(data)
    f.close()


from workPool import WorkerPoolSerial, WorkerPoolThreads

def grabFeed(l):
    print "Grabbing: ", l
    return feedparser.parse(l)

def makeGrabber(l):
    return lambda: grabFeed(l)

def makeListOfFilesToGet():
    newItems=[]
    wq = WorkerPoolThreads(10)

    rows=[r for r in con.cursor().execute("select * from podCast;")]

    for r in rows:
        l = r[1]
        print "Adding:",l, r[2]
        wq.addTask(r[2], makeGrabber(l))
        
    for r,feed in wq:
        print "PE:", r
        newItems += processEntries(feed['entries'], r)

    wq.stop()
    return newItems
    
def getArgHash():
    justArgs = sys.argv[1:]    
    arguments = {}    
    for a in justArgs:  
        try:
            arg_split = a.split('=')        
            k = arg_split[0]
            v = "=".join(arg_split[1:])
        except ValueError:
            k = a
            v = True
        arguments[k]=v
    #print "Args:", arguments
    return arguments

def addFeed(con, url):
    print "Adding", url, "to podtrackdb"
    f = feedparser.parse(url)
    t = f.feed.title
    print t
    con.cursor().execute('insert into podCast(pName, pUrl) values (:n, :u);', {'u': url, 'n': ''})
    con.commit()

def dumpOpml():
    c = con.cursor()
    c.execute('select pName, pUrl from podCast order by pName;')
    print '<?xml version="1.0" encoding="ISO-8859-1"?>'
    print '<!-- OPML generated by podtrack on ', str(datetime.datetime.now()), ' -->'
    print '<opml version="1.1">'
    for r in c:
        line = '<outline text="'
        
        if r[0]=="":
            line += r[1]
        else:
            line += r[0]
        line += '" xmlUrl="'
        line += r[1] + '"/>'
        print line
    print '</body></opml>'

if __name__ == "__main__":
    con = sqlite.connect('podtrack.db')

    args = getArgHash()

    argList = ['--add', '--list', '--opml', '--help', '--nothing']

    if '--add' in args:
        url = args['--add']
        addFeed(con, url)
        sys.exit(0)

    if '--list' in args:
        c = con.cursor()
        c.execute('select pName, pUrl from podCast order by pName;')
        print "List of podcasts:"
        for r in c:
            if r[0]=="":
                print r[1]
            else:
                print r[0]
        sys.exit(0)

    if '--opml' in args:
        dumpOpml()
        sys.exit(0)       

    if '--help' in args:
        print "No help yet:", args['--help']
        print argList
        sys.exit(0)

    if '--nothing' in args:
        print "Doing nothing:", args['--nothing']
        sys.exit(0)

    ar=makeListOfFilesToGet()

    #print repr(ar)
    #print repr(filesToDl)

    audioDir = con.cursor().execute('select pVal from podConfig;').fetchone()[0]

#for f in `ls` ; do mv $f `echo $f | sed 's/\?.*$//'` ; done
    f=open('get.sh', 'w')
    for l in ar: #filesToDl:
        f.write('wget ' + l + '\n')
    f.close()

